const url = "https://www.byrdbrothershvac.com";

export async function GET() {
  return new Response(
    `
    <?xml version="1.0" encoding="UTF-8" ?>
<urlset
	xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xhtml="https://www.w3.org/1999/xhtml"
	xmlns:mobile="https://www.google.com/schemas/sitemap-mobile/1.0"
	xmlns:news="https://www.google.com/schemas/sitemap-news/0.9"
	xmlns:image="https://www.google.com/schemas/sitemap-image/1.1"
	xmlns:video="https://www.google.com/schemas/sitemap-video/1.1"
		>
	<url>
		<loc>${url}</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
	<url>
		<loc>${url}/services</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
	<url>
		<loc>${url}/services/air_conditioning</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
	<url>
		<loc>${url}/services/air_conditioning/emergency</loc>
		<lastmod>2023-10-16</lastmod>
	</url>
	<url>
		<loc>${url}/services/air_conditioning/installation</loc>
		<lastmod>2023-10-16</lastmod>
	</url>
	<url>
		<loc>${url}/services/air_conditioning/maintenance</loc>
		<lastmod>2023-10-18</lastmod>
	</url>
	<url>
		<loc>${url}/services/air_conditioning/repair</loc>
		<lastmod>2023-10-18</lastmod>
	</url>
	<url>
		<loc>${url}/services/air_quality</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
	<url>
		<loc>${url}/services/heating</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
	<url>
		<loc>${url}/services/insulation</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
	<url>
		<loc>${url}/services/heating</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
	<url>
		<loc>${url}/services/maintenance_program</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/contact</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
    <url>
		<loc>${url}/contact/front_desk</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
    <url>
		<loc>${url}/contact/quote_form</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
    <url>
		<loc>${url}/about</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
    <url>
		<loc>${url}/about/meet_team</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
    <url>
		<loc>${url}/about/service_area</loc>
		<lastmod>2023-10-22</lastmod>
	</url>
    <url>
		<loc>${url}/about/service_area/sweeny</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/about/service_area/brazoria</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/about/service_area/lake_jackson</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/about/partners</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/products</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/products/ruud</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/products/mrcool</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/products/generac</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/products/attic_tent</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
    <url>
		<loc>${url}/products/air_scrubber</loc>
		<lastmod>2024-02-07</lastmod>
	</url>
</urlset>
    `.trim(),
    {
      headers: {
        "Content-Type": "application/xml",
      },
    }
  );
}
